services:
  app-2:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/application/src
    depends_on:
      - db-2
    environment:
      - DB_HOST=db-2
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    networks:
      - app-net
  db-2:
    container_name: db-2
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net
volumes:
  db-data:
  build_cache:
networks:
  app-net:
