name: Build & Run Dockerfile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (pour multi-arch, optionnel ici)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHRC_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6

        with:
          context: .
          file: Dockerfile
          load: true
          tags: ci-test:latest
          cache-from: type=gha,ref=${{github.ref}}
          cache-to: type=gha,ref=${{github.ref}},mode=max
          github-token: ${{ secrets.GHRC_TOKEN }}

      - name: Run container
        run: |
          docker run --rm ci-test:latest
